# Generated by Django 5.0.9 on 2026-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_subject_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'session_number']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Lets the same subject be marked more than once on the same day (e.g. two periods of Physics). Session 1, Session 2, etc.'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date', 'session_number')},
        ),
    ]
